### ISSUE TITLE
How to handle views wider than 254 columns?

### ISSUE THREAD

**Issue by rowandavies** [ottogroup/schedoscope#135]
Reading the Wiki, it's unclear what to do when you when you have more than 254 columns, which is the limit on the number of fields in a case class, inherited from the jvm limit on the number of constructor/method parameters.

My organisation ingests a lot of such tables, currently we use a variant of scrooge that we developed ourselves as an open source project:
    https://github.com/CommBank/humbug

**Comment by utzwestermann** [comment]
Hello Rowan,

sorry for the late reply, but I was struck down by a vicious cold. 

As far as I know, the Scala case class limit you are talking about applies to case class constructor vals. Schedoscope uses those for the specification of Hive partition columns, not for regular columns. So should your tables have more than 254 partition columns, you would end up in a problem. But Hive metastore performance would kill you way earlier than that...

Normal Hive table columns are declared in Schedoscope views using fields within the body of the case class, for which I think there is no such limit. 

Example:

case class Click(
                 // There is a limit here
                 shopCode: Parameter[String],
                 year: Parameter[String],
                 month: Parameter[String],
                 day: Parameter[String]) extends View {
 
  // no limit
  val id = fieldOf[String]
  val url = fieldOf[String]
}

Hope that helps.

Cheers,

Utz
