### ISSUE TITLE
schedoscope-tutorial-osm-data

### ISSUE THREAD

**Issue by muzhongjiang** [ottogroup/schedoscope#75]
```
    <dependency>
        <groupId>schedoscope</groupId>
        <artifactId>schedoscope-tutorial-osm-data</artifactId>
        <version>0.1.1</version>
    </dependency>
```

===================Where is the jar ? ========================================

**Comment by ktohme** [comment]
If you have build Schedoscope with maven, the jar should be found in your local maven repository. If you are using the Cloudera QuickStart VM, it should be found at `/home/cloudera/.m2/repository/schedoscope/schedoscope-tutorial-osm-data/0.1.1/schedoscope-tutorial-osm-data-0.1.1.jar`.

This jar is located at our bintray repository: `https://dl.bintray.com/ottogroup/maven/schedoscope/schedoscope-tutorial-osm-data/0.1.1/:schedoscope-tutorial-osm-data-0.1.1.jar`
