### ISSUE TITLE
Unlimited Retries of failed Transformations

### ISSUE THREAD

**Issue by lofifnc** [ottogroup/schedoscope#97]
Failed Transformation will be retried indefinitely if a RetryableDriverException is thrown.

**Comment by ghost** [comment]
This is the protocol, yes. One needs to look at the particular error case and make sure, that a retryable driver exception is not thrown.

Additionally, we could add a maximum number of retries for RetryableDriverExceptions.

Am 26.07.2016 10:41 schrieb Alexander Kolb notifications@github.com:

Failed Transformation will be retried indefinitely if a RetryableDriverException is thrown.

##

**Comment by utzwestermann** [comment]
I don't think limiting RetryableDriverExceptions makes sense. One needs to take care that drivers answer with transformation failed if unlimited retries are not wanted
